window: 5
horizon: 5
batch_size: 64
l2_reg: 0.0001
use_lr_schedule: True
lr: 0.0001

hidden_size: 32
ff_size: 256
n_layers: 8
dropout: 0.3
temporal_kernel_size: 2
spatial_kernel_size: 2
dilation: 2
dilation_mod: 2
norm: none
learned_adjacency: True