window: 100
horizon: 1
batch_size: 64
l2_reg: 0.0001
use_lr_schedule: True
lr: 0.0001
epochs: 500

hidden_size: 32
ff_size: 256
n_layers: 4
dropout: 0.1
temporal_kernel_size: 2
spatial_kernel_size: 2
dilation: 2
norm: none